/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/t2.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/t2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials.ComputerMouse_mat1} />
      <mesh name="Table" geometry={nodes.Table.geometry} material={materials['Material.001']} />
      <mesh name="sleeping_pikachu" geometry={nodes.sleeping_pikachu.geometry} material={nodes.sleeping_pikachu.material} />
      <mesh name="Mug" geometry={nodes.Mug.geometry} material={materials.phong1SG} />
      <mesh name="Keyboard1" geometry={nodes.Keyboard1.geometry} material={materials.lambert3SG} />
      <mesh name="plant" geometry={nodes.plant.geometry} material={materials.FiddleleafFigPottedPlant_mat} />
      <group name="Ukulele" position={[0.649, 0.821, -2.911]} rotation={[1.307, -1.248, 2.669]}>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Frets&Nut']} />
        <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials['Trim&Extra']} />
        <mesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials.Strings} />
        <mesh name="Cylinder_3" geometry={nodes.Cylinder_3.geometry} material={materials.LightWood} />
        <mesh name="Cylinder_4" geometry={nodes.Cylinder_4.geometry} material={materials.DarkWood} />
        <mesh name="Cylinder_5" geometry={nodes.Cylinder_5.geometry} material={materials.Extra2} />
        <mesh name="Cylinder_6" geometry={nodes.Cylinder_6.geometry} material={materials['Metal.001']} />
      </group>
      <mesh name="Shelf" geometry={nodes.Shelf.geometry} material={materials['wall-shelf-063.001']} />
      <mesh name="OfficeChair001" geometry={nodes.OfficeChair001.geometry} material={materials['Grey.001']} />
      <mesh name="OfficeChair001_1" geometry={nodes.OfficeChair001_1.geometry} material={materials['Black.001']} />
      <mesh name="OfficeChair001_2" geometry={nodes.OfficeChair001_2.geometry} material={materials['Chair.001']} />
      <mesh name="mesh1173329792001" geometry={nodes.mesh1173329792001.geometry} material={materials['mat17.001']} />
      <mesh name="mesh1173329792001_1" geometry={nodes.mesh1173329792001_1.geometry} material={materials['mat18.001']} />
      <mesh name="mesh1173329792001_2" geometry={nodes.mesh1173329792001_2.geometry} material={materials['mat23.001']} />
      <mesh name="Monitor1002" geometry={nodes.Monitor1002.geometry} material={materials['Plastic1Monitor1.002']} />
      <mesh name="Monitor1002_1" geometry={nodes.Monitor1002_1.geometry} material={materials['Screen1Monitor1.002']} />
    </group>
  )
}

useGLTF.preload('/t2.glb')
